fragment TaskFields on Task {
  id
  name
  parent {
    id
    name
  }
  folders { 
    id
    name
  }
  assignees {
    id
    name
  }
  creator {
    id
    name
  }
  shareWith
  startDate
  finishDate
  importance
  status
}

fragment CommentFields on Comment {
  id
  body
  user {
    id
    name
    initials
    avatarColor
  }
}

mutation CaptureEmail($email: String!) {
  captureEmail(email: $email) {
    id
    email      
  }
}

mutation Signup($id: String!, $name: String!, $password: String!) {
  signup(id: $id, name: $name, password: $password) {
    token
    user {
      id
      email
    }
  }
}

mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      id
      email
    }
  }
}

query FolderTree {
  folderTree
}

mutation CreateTask($folder: String, $parent: String, $name: String!) {
  createTask(folder: $folder, parent: $parent, name: $name) {
    ...TaskFields 
  }
}

mutation UpdateTask($id: String!, $name: String) {
  updateTask(id: $id, name: $name) {
    ...TaskFields
  }
}

mutation DeleteTask($id: String!) {
  deleteTask(id: $id)
}

query GetFolders($ids: [String]) {
  getFolders(ids: $ids) {
    id
    name
    subfolders
  }
}

query GetFolder($id: String!) {
  getFolder(id: $id) {
    id
    name
    shareWith
  }
}

query GetTasks($parent: String, $folder: String) {
  getTasks(parent: $parent, folder: $folder) {
    ...TaskFields
  }
}

query GetTask($id: String!) {
  getTask(id: $id) {
    ...TaskFields
  }
}

query GetComments($parent: String) {
  getComments(parent: $parent) {
    ...CommentFields
  }
}

mutation CreateComment($body: String, $parent: ShareInput) {
  createComment(body: $body, parent: $parent) {
    ...CommentFields
  }
}