mutation CaptureEmail($email: String!) {
  captureEmail(email: $email) {
    id
    email      
  }
}

mutation Signup($id: String!, $name: String!, $password: String!) {
  signup(id: $id, name: $name, password: $password) {
    token
    user {
      id
      email
    }
  }
}

mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      id
      email
    }
  }
}

query FolderTree {
  folderTree
}

mutation CreateTask($folder: String, $parent: String, $name: String!) {
  createTask(folder: $folder, parent: $parent, name: $name) {
    id
    name
    status
    subtasks
  }
}

mutation UpdateTask($id: String!, $name: String) {
  updateTask(id: $id, name: $name) {
    id
    name
    status
    subtasks
  }
}

mutation DeleteTask($id: String!, $parent: String) {
  deleteTask(id: $id, parent: $parent)
}

query GetFolder($id: String!) {
  getFolder(id: $id) {
    id
    name
    shareWith
    tasks {
      id
      name
      status
      subtasks
    }
  }
}

query GetTask($id: String!) {
  getTask(id: $id) {
    id
    name
    parent {
      id
      name
    }
    folders { 
      id
      name
    }
    assignees {
      id
      name
    }
    creator {
      id
      name
    }
    comments {
      id
      body
      user {
        id
        name
        initials
        avatarColor
      }
    }
    shareWith
    startDate
    finishDate
    importance
    status
    subtasks
  }
}