mutation CaptureEmail($email: String!) {
  captureEmail(email: $email) {
    id
    email      
  }
}

mutation Signup($id: String!, $name: String!, $password: String!) {
  signup(id: $id, name: $name, password: $password) {
    token
    user {
      id
      email
    }
  }
}

mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      id
      email
    }
  }
}